#!/bin/bash

git archive $1 | bzip2 > projet-reseaux.tar.bz2

scp ~/projet-reseaux---netradio/projet-reseaux.tar.bz2 $2@nivose.informatique.univ-paris-diderot.fr:~/PR6/Projet

rm projet-reseaux.tar.bz2

ssh lulu.ext
